// Dev-time warding extractor. Pulls warded keyway cross-sections from a local
// clone of ervanalb/keygen (CC0) and regenerates the bundled data:
//   docs/key-refs/derived/warding-profiles.json  (full raw extract, all sections)
//   js/keys/warding.js                            (in-scope subset, importable)
//
// keygen is a DEV-TIME SOURCE, not a runtime dependency — the app ships only the
// extracted static polygons. Re-run this when adding keyways.
//
//   git clone https://github.com/ervanalb/keygen.git   # anywhere
//   node scripts/extract-warding.mjs /path/to/keygen    # or set KEYGEN=/path
//   (npm run warding  uses ./keygen or $KEYGEN by default)

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const keygen = process.argv[2] || process.env.KEYGEN || path.join(root, 'keygen');
const scadDir = path.join(keygen, 'scad');

if (!fs.existsSync(scadDir)) {
  console.error(`keygen scad/ not found at ${scadDir}\n` +
    `Clone it first:  git clone https://github.com/ervanalb/keygen.git\n` +
    `then:            node scripts/extract-warding.mjs /path/to/keygen`);
  process.exit(1);
}

// Which sections ship in js/keys/warding.js. Scope is authorization-based (see
// blanks.js); this list is just what we've wired so far. Add keyways here.
const INSCOPE = {
  schlage: ['c', 'ce', 'e', 'ef', 'f', 'fg', 'g', 'h', 'j', 'k', 'l'],
  kwikset: ['kw1'],
  master: ['k1'],
  best: ['a', 'b', 'c'],
};

// Parse `name = [[x,y],...];` numeric point arrays from an OpenSCAD source.
function parseArrays(text) {
  const out = {};
  const re = /([A-Za-z_]\w*)\s*=\s*(\[\[[\s\S]*?\]\])\s*;/g;
  let m;
  while ((m = re.exec(text))) {
    const pts = [...m[2].matchAll(/\[\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\]/g)]
      .map(p => [parseFloat(p[1]), parseFloat(p[2])]);
    if (pts.length >= 3) out[m[1]] = pts;
  }
  return out;
}

const round = (n, d = 4) => Number(n.toFixed(d));

// Centre on X (thickness), shift Y so the blade back sits at 0.
function normalise(poly) {
  const xs = poly.map(p => p[0]), ys = poly.map(p => p[1]);
  const cx = 0.5 * (Math.min(...xs) + Math.max(...xs)), y0 = Math.min(...ys);
  return {
    profile: poly.map(p => [round(p[0] - cx), round(p[1] - y0)]),
    thickness: round(Math.max(...xs) - Math.min(...xs)),
    height: round(Math.max(...ys) - Math.min(...ys)),
  };
}

const lib = {};
for (const fn of fs.readdirSync(scadDir)) {
  if (!fn.endsWith('.gen.scad')) continue;
  const mfr = fn.replace('.gen.scad', '');
  const arrs = parseArrays(fs.readFileSync(path.join(scadDir, fn), 'utf8'));
  for (const [name, poly] of Object.entries(arrs)) {
    const mm = name.match(/^warding_(.+)_points$/);
    if (!mm) continue;
    (lib[mfr] ||= {})[mm[1]] = normalise(poly);
  }
}

// Full raw extract.
const jsonPath = path.join(root, 'docs/key-refs/derived/warding-profiles.json');
fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
const rawOut = {};
for (const [mfr, secs] of Object.entries(lib)) {
  rawOut[mfr] = {};
  for (const [s, d] of Object.entries(secs)) {
    rawOut[mfr][s] = { thickness_mm: d.thickness, height_mm: d.height, n: d.profile.length, profile_mm: d.profile };
  }
}
fs.writeFileSync(jsonPath, JSON.stringify(rawOut, null, 1) + '\n');

// In-scope importable module.
const L = [];
L.push('// Warded keyway cross-sections (blade end-on), in millimetres.');
L.push('//');
L.push('// GENERATED by scripts/extract-warding.mjs from ervanalb/keygen (CC0 1.0,');
L.push('// public domain). Do not edit by hand — re-run `npm run warding`. Each profile');
L.push('// is centred on X (thickness) with Y from 0 (blade back) up to the blade top.');
L.push('// Extrude one along the blade to make a key that enters the lock (a flat blade');
L.push('// will not, for paracentric keyways like Schlage C or BEST A).');
L.push('//');
L.push('// Scope is authorization-based (see blanks.js); this is the wired-in subset.');
L.push('// keygen also carries Medeco high-security sections — see the full raw extract');
L.push('// docs/key-refs/derived/warding-profiles.json to add more.');
L.push('');
L.push('export const WARDING = {');
let count = 0;
for (const [mfr, secs] of Object.entries(INSCOPE)) {
  for (const s of secs) {
    const d = lib[mfr]?.[s];
    if (!d) { console.error(`WARN: ${mfr}:${s} not found in keygen`); continue; }
    const pts = d.profile.map(([x, y]) => `[${x},${y}]`).join(', ');
    L.push(`  ${JSON.stringify(`${mfr}:${s}`)}: { thickness: ${d.thickness}, height: ${d.height}, profile: [${pts}] },`);
    count++;
  }
}
L.push('};');
L.push('');
L.push('export function getWarding(id) { return WARDING[id] || null; }');
L.push('');
fs.writeFileSync(path.join(root, 'js/keys/warding.js'), L.join('\n'));

console.log(`Extracted ${Object.values(lib).reduce((a, s) => a + Object.keys(s).length, 0)} sections ` +
  `across ${Object.keys(lib).length} manufacturers → warding-profiles.json`);
console.log(`Wrote ${count} in-scope profiles → js/keys/warding.js`);
