// Copyright (C) 2026 Projects and Mods
// GPL-3.0-or-later WITH Commons Clause (non-commercial) - see LICENSE.

// Dev-time warding extractor. Pulls warded keyway cross-sections from a local
// clone of ervanalb/keygen (CC0) and regenerates the bundled data:
//   docs/key-refs/derived/warding-profiles.json  (full raw extract, all sections)
//   js/keys/warding.js                            (in-scope subset, importable)
//
// keygen is a DEV-TIME SOURCE, not a runtime dependency — the app ships only the
// extracted static polygons. Re-run this when adding keyways.
//
//   git clone https://github.com/ervanalb/keygen.git   # anywhere
//   node scripts/extract-warding.mjs /path/to/keygen    # or set KEYGEN=/path
//   (npm run warding  uses ./keygen or $KEYGEN by default)

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const keygen = process.argv[2] || process.env.KEYGEN || path.join(root, 'keygen');
const scadDir = path.join(keygen, 'scad');

if (!fs.existsSync(scadDir)) {
  console.error(`keygen scad/ not found at ${scadDir}\n` +
    `Clone it first:  git clone https://github.com/ervanalb/keygen.git\n` +
    `then:            node scripts/extract-warding.mjs /path/to/keygen`);
  process.exit(1);
}

// Which sections ship in js/keys/warding.js. Scope is authorization-based (see
// blanks.js); this list is just what we've wired so far. Add keyways here.
const INSCOPE = {
  schlage: ['c', 'ce', 'e', 'ef', 'f', 'fg', 'g', 'h', 'j', 'k', 'l'],
  kwikset: ['kw1'],
  master: ['k1'],
  best: ['a', 'b', 'c'],
};

// Parse `name = [[x,y],...];` numeric point arrays from an OpenSCAD source.
function parseArrays(text) {
  const out = {};
  const re = /([A-Za-z_]\w*)\s*=\s*(\[\[[\s\S]*?\]\])\s*;/g;
  let m;
  while ((m = re.exec(text))) {
    const pts = [...m[2].matchAll(/\[\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\]/g)]
      .map(p => [parseFloat(p[1]), parseFloat(p[2])]);
    if (pts.length >= 3) out[m[1]] = pts;
  }
  return out;
}

const round = (n, d = 4) => Number(n.toFixed(d));

// Centre on X (thickness), shift Y so the blade back sits at 0.
function normalise(poly) {
  const xs = poly.map(p => p[0]), ys = poly.map(p => p[1]);
  const cx = 0.5 * (Math.min(...xs) + Math.max(...xs)), y0 = Math.min(...ys);
  return {
    profile: poly.map(p => [round(p[0] - cx), round(p[1] - y0)]),
    thickness: round(Math.max(...xs) - Math.min(...xs)),
    height: round(Math.max(...ys) - Math.min(...ys)),
  };
}

const lib = {};
for (const fn of fs.readdirSync(scadDir)) {
  if (!fn.endsWith('.gen.scad')) continue;
  const mfr = fn.replace('.gen.scad', '');
  const arrs = parseArrays(fs.readFileSync(path.join(scadDir, fn), 'utf8'));
  for (const [name, poly] of Object.entries(arrs)) {
    const mm = name.match(/^warding_(.+)_points$/);
    if (!mm) continue;
    (lib[mfr] ||= {})[mm[1]] = normalise(poly);
  }
}

// Full raw extract.
const jsonPath = path.join(root, 'docs/key-refs/derived/warding-profiles.json');
fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
const rawOut = {};
for (const [mfr, secs] of Object.entries(lib)) {
  rawOut[mfr] = {};
  for (const [s, d] of Object.entries(secs)) {
    rawOut[mfr][s] = { thickness_mm: d.thickness, height_mm: d.height, n: d.profile.length, profile_mm: d.profile };
  }
}
fs.writeFileSync(jsonPath, JSON.stringify(rawOut, null, 1) + '\n');

// In-scope importable module.
const LICENSE_HEADER = [
  '// Copyright (C) 2026 Projects and Mods',
  '// GPL-3.0-or-later WITH Commons Clause (non-commercial) - see LICENSE.',
  '',
];
const L = [...LICENSE_HEADER];
L.push('// Warded keyway cross-sections (blade end-on), in millimetres.');
L.push('//');
L.push('// GENERATED by scripts/extract-warding.mjs from ervanalb/keygen (CC0 1.0,');
L.push('// public domain). Do not edit by hand — re-run `npm run warding`. Each profile');
L.push('// is centred on X (thickness) with Y from 0 (blade back) up to the blade top.');
L.push('// Extrude one along the blade to make a key that enters the lock (a flat blade');
L.push('// will not, for paracentric keyways like Schlage C or BEST A).');
L.push('//');
L.push('// Scope is authorization-based (see blanks.js); this is the wired-in subset.');
L.push('// keygen also carries Medeco high-security sections — see the full raw extract');
L.push('// docs/key-refs/derived/warding-profiles.json to add more.');
L.push('');
L.push('export const WARDING = {');
let count = 0;
for (const [mfr, secs] of Object.entries(INSCOPE)) {
  for (const s of secs) {
    const d = lib[mfr]?.[s];
    if (!d) { console.error(`WARN: ${mfr}:${s} not found in keygen`); continue; }
    const pts = d.profile.map(([x, y]) => `[${x},${y}]`).join(', ');
    L.push(`  ${JSON.stringify(`${mfr}:${s}`)}: { thickness: ${d.thickness}, height: ${d.height}, profile: [${pts}] },`);
    count++;
  }
}
L.push('};');
L.push('');
L.push('export function getWarding(id) { return WARDING[id] || null; }');
L.push('');
fs.writeFileSync(path.join(root, 'js/keys/warding.js'), L.join('\n'));

// ── Bows ─────────────────────────────────────────────────────────────────────
// Extract each keyway's bow (head) from its key outline. keygen positions the
// key by a shoulder-datum offset (indices below, taken from the *.scad drivers);
// we apply it, re-derive the blade back geometrically, orient so the blade is at
// +x, and lift out the bow-side loop run (bow at −x, blade back at h=0).
function parsePaths(text, name) {
  const m = text.match(new RegExp(name + '\\s*=\\s*(\\[[\\s\\S]*?\\])\\s*;'));
  return m ? [...m[1].matchAll(/\[([\d,\s]+)\]/g)].map(g => g[1].split(',').map(n => parseInt(n, 10))) : null;
}
const BOW_CFG = {  // gen file, outline var, shoulder-datum indices [x-from, y-from]
  schlage: { gen: 'schlage.gen.scad', var: 'outline_5pin_points', ox: 92, oy: 98 },
  kwikset: { gen: 'kwikset.gen.scad', var: 'outline_points', ox: 34, oy: 26 },
  master: { gen: 'master.gen.scad', var: 'outline_k1_points', ox: 61, oy: 40 },
  // BEST (SFIC) is drawn in a FLIPPED frame: its datum (points 42/37) sits at the
  // TIP and the key extends −x with cuts at negative locations ("tip to bow"),
  // opposite the others. So we don't flip; instead we set the blade back from the
  // tip region and re-shift x so the shoulder (where the outline widens past the
  // blade height) lands at 0 — then the same bow-run extraction applies.
  best: { gen: 'best.gen.scad', var: 'outline_points', ox: 42, oy: 37, tipDatum: true, bladeTop: 8.382 },
};
const bows = {};
for (const [id, cfg] of Object.entries(BOW_CFG)) {
  const text = fs.readFileSync(path.join(scadDir, cfg.gen), 'utf8');
  const P = parseArrays(text)[cfg.var];
  if (!P) { console.error(`WARN: bow ${id} outline not found`); continue; }
  const paths = parsePaths(text, cfg.var.replace('_points', '_paths'));
  const dx = -P[cfg.ox][0], dy = -P[cfg.oy][1];
  const Q = P.map(([x, y]) => [x + dx, y + dy]);
  const outer = (paths && paths[0]) ? paths[0].map(i => Q[i]) : Q;
  let B;
  if (cfg.tipDatum) {
    // Tip-datum frame (BEST): blade already runs +x from the tip; back = min y over
    // the blade (tip) region; shoulder = first x (tip→bow) whose top exceeds the
    // blade top; shift so shoulder→0.
    const maxX = Math.max(...outer.map(p => p[0]));
    const spine = Math.min(...outer.filter(p => p[0] > maxX - 28).map(p => p[1]));
    const S = outer.map(([x, h]) => [x, h - spine]);
    const dense = []; for (let i = 0; i < S.length; i++) { const a = S[i], b = S[(i + 1) % S.length]; const L = Math.hypot(b[0] - a[0], b[1] - a[1]), n = Math.max(1, Math.round(L / 0.5)); for (let k = 0; k < n; k++) dense.push([a[0] + (b[0] - a[0]) * k / n, a[1] + (b[1] - a[1]) * k / n]); }
    let sh = Math.min(...S.map(p => p[0]));
    for (let x = maxX; x > sh; x -= 0.5) { const near = dense.filter(p => Math.abs(p[0] - x) < 0.6); if (near.length && Math.max(...near.map(p => p[1])) > cfg.bladeTop + 1.5) { sh = x; break; } }
    B = S.map(([x, h]) => [x - sh, h]);
  } else {
    const span = (f) => { const ys = outer.filter(f).map(p => p[1]); return ys.length ? Math.max(...ys) - Math.min(...ys) : 1e9; };
    const flip = span(p => p[0] > 0) < span(p => p[0] < 0) ? 1 : -1; // blade to +x
    const X = outer.map(p => p[0] * flip);
    const spine = Math.min(...outer.filter((_, i) => X[i] > 1).map(p => p[1]));
    B = outer.map((p, i) => [X[i], p[1] - spine]);
  }
  const on = B.map(p => p[0] < -0.3);
  const runs = []; let cur = [];
  for (let i = 0; i < B.length; i++) { if (on[i]) cur.push(i); else if (cur.length) { runs.push(cur); cur = []; } }
  if (cur.length) runs.push(cur);
  if (on[0] && on[B.length - 1] && runs.length > 1) { runs[0] = runs[runs.length - 1].concat(runs[0]); runs.pop(); }
  const run = runs.sort((a, b) => b.length - a.length)[0];
  bows[id] = run.map(i => [round(B[i][0], 3), round(B[i][1], 3)]);
}
const BL = [...LICENSE_HEADER];
BL.push('// Manufacturer bow silhouettes (the head you grip), in mm, in the blade\'s');
BL.push('// (x=length, h=height) plane with the blade back at h=0 and the shoulder near');
BL.push('// x=0 (bow extends to negative x).');
BL.push('//');
BL.push('// GENERATED by scripts/extract-warding.mjs from ervanalb/keygen (CC0 1.0).');
BL.push('// Do not edit by hand — re-run `npm run warding`. Open chain (neck end left');
BL.push('// open); keyMesh bridges it into the blade. BEST (SFIC) is de-skewed from its');
BL.push('// flipped tip-datum frame (see BOW_CFG.best) so its real head is now included.');
BL.push('');
BL.push('export const BOWS = {');
for (const [id, b] of Object.entries(bows)) {
  BL.push(`  ${id}: [${b.map(([x, h]) => `[${x},${h}]`).join(', ')}],`);
}
BL.push('};');
BL.push('');
BL.push('export function getBow(id) { return BOWS[id] || null; }');
BL.push('');
fs.writeFileSync(path.join(root, 'js/keys/bows.js'), BL.join('\n'));

console.log(`Extracted ${Object.values(lib).reduce((a, s) => a + Object.keys(s).length, 0)} sections ` +
  `across ${Object.keys(lib).length} manufacturers → warding-profiles.json`);
console.log(`Wrote ${count} in-scope profiles → js/keys/warding.js`);
console.log(`Wrote ${Object.keys(bows).length} bows → js/keys/bows.js`);
